name: "Mael's Custom Jenkins Agent Image"
on: [ push ]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Login to Docker Hub'
        uses: 'docker/login-action@v2'
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - run: './build.sh'